// Resource URLs aren't set yet - these will render as plain text until real
// links are provided, since fabricating destination URLs would risk sending
// students to the wrong (or a nonexistent) page.
export const CAMPUS_RESOURCES = {
  "UC Berkeley": { reuse: "ReUSE Berkeley", donation: "Berkeley Reuse & Donation Resources", ewaste: "UC Berkeley Cal Zero Waste – Reuse" },
  "UC Davis": { reuse: "Aggies Give & Go / Move-Out Donation Drive", donation: "City of Davis – Waste Reduction & Reuse", ewaste: "UC Davis – Bulk Recycling & Disposal" },
  "UC Irvine": { reuse: "UCI Move-Out Donation Drive", donation: "UCI Basic Needs Center", ewaste: "UC Irvine – Housing Move-Out" },
  "UCLA": { reuse: "Sustainable Bruin Move Out", donation: "UCLA Surplus Stop", ewaste: "Los Angeles S.A.F.E. Centers" },
  "UC Merced": { reuse: "UC Merced Sustainability", donation: "UC Merced Housing & Residential Education", ewaste: "CalRecycle – Electronic Waste Resources" },
  "UC Riverside": { reuse: "UCR Sustainability", donation: "UCR Housing, Dining & Hospitality", ewaste: "CalRecycle – Electronic Waste Resources" },
  "UC San Diego": { reuse: "UCSD Sustainable Move-Out Campaign", donation: "The Hub Basic Needs Center – Donations", ewaste: "UCSD Sustainable Move-Out / E-Waste Resources" },
  "UC San Francisco": { reuse: "UCSF Surplus Property", donation: "Goodwill Donation Locator", ewaste: "CalRecycle – Electronic Waste" },
  "UC Santa Barbara": { reuse: "UCSB Move-Out Sale Donations", donation: "Isla Vista Community Services District – Move-Out Resources", ewaste: "UCSB Surplus Sales" },
  "UC Santa Cruz": { reuse: "UCSC Move-Out Resources", donation: "Goodwill Central Coast", ewaste: "Santa Cruz County Recycling & Disposal" },
  "CSU Bakersfield": { reuse: "CSUB Sustainability", donation: "Goodwill Southern California Donation Locator", ewaste: "CalRecycle – Electronic Waste" },
  "CSU Channel Islands": { reuse: "CSUCI Sustainability", donation: "Goodwill Donation Locator", ewaste: "CalRecycle – Electronic Waste" },
  "Chico State": { reuse: "Chico State Sustainability", donation: "Goodwill Donation Locator", ewaste: "Butte County Recycling Resources" },
  "CSU Dominguez Hills": { reuse: "CSUDH Sustainability", donation: "Goodwill Southern California", ewaste: "Los Angeles County Household Hazardous Waste" },
  "CSU East Bay": { reuse: "CSUEB Sustainability", donation: "Goodwill Donation Locator", ewaste: "Alameda County Household Hazardous Waste" },
  "Fresno State": { reuse: "Fresno State Sustainability", donation: "Goodwill Industries of San Joaquin Valley", ewaste: "Fresno County Recycling Resources" },
  "Cal State Fullerton": { reuse: "CSUF Sustainability", donation: "Goodwill of Orange County", ewaste: "Orange County Household Hazardous Waste" },
  "Cal Poly Humboldt": { reuse: "Humboldt Donation Dash", donation: "Humboldt Sustainability / WRRAP", ewaste: "Humboldt County Hazardous Waste" },
  "Cal State Long Beach": { reuse: "CSULB Sustainability", donation: "City of Long Beach Donation Guide", ewaste: "Long Beach Household Hazardous Waste" },
  "Cal State LA": { reuse: "Cal State LA Housing Move-Out", donation: "Goodwill Southern California", ewaste: "Los Angeles S.A.F.E. Centers" },
  "Cal Maritime": { reuse: "Cal Maritime Sustainability", donation: "Goodwill Donation Locator", ewaste: "CalRecycle – Electronic Waste" },
  "CSU Monterey Bay": { reuse: "CSUMB Sustainability", donation: "Goodwill Central Coast", ewaste: "Monterey County Recycling Resources" },
  "CSUN": { reuse: "CSUN Matador Move-Out", donation: "Goodwill Southern California", ewaste: "Los Angeles S.A.F.E. Centers" },
  "Cal Poly Pomona": { reuse: "Cal Poly Pomona Sustainability", donation: "Habitat for Humanity ReStore Locator", ewaste: "CalRecycle – Electronic Waste" },
  "Sacramento State": { reuse: "Sacramento State Sustainability", donation: "Goodwill Sacramento Valley & Northern Nevada", ewaste: "Sacramento County Recycling & Waste" },
  "Cal State San Bernardino": { reuse: "CSUSB Sustainability", donation: "Goodwill Southern California", ewaste: "San Bernardino County Recycling" },
  "San Diego State": { reuse: "SDSU Housing Sustainability / Give It Up Drive", donation: "Goodwill San Diego", ewaste: "City of San Diego E-Waste & Household Hazardous Waste" },
  "San Francisco State": { reuse: "SFSU Sustainability", donation: "Goodwill San Francisco Bay", ewaste: "San Francisco Recology – E-Waste & Reuse" },
  "San José State": { reuse: "SJSU Sustainability", donation: "City of San José Donation Resources", ewaste: "Santa Clara County Recycling & E-Waste" },
  "Cal Poly San Luis Obispo": { reuse: "CP Thrift", donation: "City of San Luis Obispo Donation Resources", ewaste: "Cal Poly Zero Waste" },
  "CSU San Marcos": { reuse: "CSUSM Sustainability", donation: "Goodwill San Diego", ewaste: "San Diego County Recycling Resources" },
  "Sonoma State": { reuse: "Sonoma State Move-Out Sustainable Collection Areas", donation: "Zero Waste Sonoma", ewaste: "Sonoma County Household Hazardous Waste" },
  "Stanislaus State": { reuse: "Stanislaus State Sustainability", donation: "Goodwill Industries of San Joaquin Valley", ewaste: "Stanislaus County Recycling Resources" },
};
